= Parameters

The parent key for all of the following parameters is `rabbitmq_operator`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace in which to deploy this component.

== `createNamespace`

[horizontal]
type:: boolean
default:: `true`

Whether to create the namespace defined by `namespace`.

== `namespaceLabels`

[horizontal]
type:: object
default:: `{}`

Additional labels to apply to the namespace defined by `namespace`.

== `namespaceAnnotations`

[horizontal]
type:: object
default:: `{}`

Additional annotations to apply to the namespace defined by `namespace`.

== Charts Configuration

The component deploys four Helm charts from GHCR OCI registries.
Each chart is referenced by its OCI source and version.

=== `charts.rabbitmq-crd.source`

[horizontal]
type:: string
default:: `oci://ghcr.io/bacluc-agent/rabbitmq-crd-chart/rabbitmq-crd`

The OCI source of the RabbitMQ CRD chart.

=== `charts.rabbitmq-crd.version`

[horizontal]
type:: string
default:: `0.0.1`

The version of the RabbitMQ CRD chart to deploy.

=== `charts.rabbitmq-operator.source`

[horizontal]
type:: string
default:: `oci://ghcr.io/bacluc-agent/rabbitmq-operator-chart/rabbitmq-operator`

The OCI source of the RabbitMQ operator chart.

=== `charts.rabbitmq-operator.version`

[horizontal]
type:: string
default:: `0.0.1`

The version of the RabbitMQ operator chart to deploy.

=== `charts.rabbitmq-instance.source`

[horizontal]
type:: string
default:: `oci://ghcr.io/bacluc-agent/rabbitmq-instance-chart/rabbitmq-instance`

The OCI source of the RabbitMQ instance chart.

=== `charts.rabbitmq-instance.version`

[horizontal]
type:: string
default:: `0.0.1`

The version of the RabbitMQ instance chart to deploy.

=== `charts.test-helm-chart.source`

[horizontal]
type:: string
default:: `oci://ghcr.io/bacluc-agent/test-helm-chart/test-helm-chart`

The OCI source of the test chart.

=== `charts.test-helm-chart.version`

[horizontal]
type:: string
default:: `0.0.1`

The version of the test chart to deploy.

== CRD Chart Configuration

=== `crd.helmValues`

[horizontal]
type:: object
default:: `{}`

Helm values passed to the RabbitMQ CRD chart.

== Operator Chart Configuration

=== `operator.helmValues.useCertManager`

[horizontal]
type:: boolean
default:: `true`

Whether to use cert-manager for certificate management.

=== `operator.helmValues.clusterOperator.image.registry`

[horizontal]
type:: string
default:: `ghcr.io`

The container registry for the cluster operator image.

=== `operator.helmValues.clusterOperator.image.repository`

[horizontal]
type:: string
default:: `rabbitmq/cluster-operator`

The repository path for the cluster operator image.

=== `operator.helmValues.msgTopologyOperator.image.registry`

[horizontal]
type:: string
default:: `docker.io`

The container registry for the messaging topology operator image.

=== `operator.helmValues.msgTopologyOperator.image.repository`

[horizontal]
type:: string
default:: `bitnamilegacy/rmq-messaging-topology-operator`

The repository path for the messaging topology operator image.

=== `operator.helmValues.rabbitmqImage.registry`

[horizontal]
type:: string
default:: `docker.io`

The container registry for the RabbitMQ image.

=== `operator.helmValues.rabbitmqImage.repository`

[horizontal]
type:: string
default:: `bitnamilegacy/rabbitmq`

The repository path for the RabbitMQ image.

=== `operator.helmValues.credentialUpdaterImage.registry`

[horizontal]
type:: string
default:: `docker.io`

The container registry for the credential updater image.

=== `operator.helmValues.credentialUpdaterImage.repository`

[horizontal]
type:: string
default:: `bitnamilegacy/rmq-default-credential-updater`

The repository path for the credential updater image.

== Instance Chart Configuration

=== `instance.helmValues.namespace`

[horizontal]
type:: string
default:: `rabbitmq_operator.rabbitmq.namespace`

The namespace in which to deploy the RabbitMQ cluster and prober, passed through to the instance chart's top-level `namespace` value.
Sourced from `rabbitmq.namespace` (default `rabbitmq`).

=== `instance.helmValues.rabbitmq`

[horizontal]
type:: object
default:: `rabbitmq_operator.rabbitmq`

The RabbitMQ cluster configuration, passed through to the instance chart.
See <<RabbitMQ Cluster Configuration>> for the supported parameters.

=== `instance.helmValues.prober`

[horizontal]
type:: object
default:: `rabbitmq_operator.prober`

The prober configuration, passed through to the instance chart.
See <<Prober Configuration>> for the supported parameters.

== Test Chart Configuration

=== `test.helmValues`

[horizontal]
type:: object
default:: `{foo: bar}`

Helm values passed to the test chart.

== RabbitMQ Cluster Configuration

=== `rabbitmq.enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy a RabbitMQ cluster instance.

=== `rabbitmq.name`

[horizontal]
type:: string
default:: `rabbitmq`

The name of the RabbitMQ cluster.

=== `rabbitmq.namespace`

[horizontal]
type:: string
default:: `rabbitmq`

The namespace in which to deploy the RabbitMQ cluster.

=== `rabbitmq.namespaceLabels`

[horizontal]
type:: object
default:: `{}`

Additional labels to apply to the RabbitMQ namespace.

=== `rabbitmq.image`

[horizontal]
type:: string
default:: `docker.io/bitnamilegacy/rabbitmq:3.11.26-debian-11-r0`

The RabbitMQ container image to use.

=== `rabbitmq.affinity`

[horizontal]
type:: object
default:: `{}`

Kubernetes affinity rules for RabbitMQ pods. If empty, no affinity will be set.

=== `rabbitmq.plugins`

[horizontal]
type:: array
default:: `[]`

List of additional RabbitMQ plugins to enable.

=== `rabbitmq.additionalConfig`

[horizontal]
type:: string
default:: `""`

Additional configuration to append to `rabbitmq.conf`.
The value is appended after the component-managed configuration entries.

The component always sets `vm_memory_high_watermark.absolute` to the value of `rabbitmq.resources.limits.memory`.
Any configuration provided here is appended after that line.

NOTE: Changing this value on an existing `RabbitmqCluster` will trigger a StatefulSet rolling restart and cause temporary RabbitMQ downtime.

=== `rabbitmq.persistence.storage`

[horizontal]
type:: string
default:: `3Gi`

The amount of persistent storage to allocate for each RabbitMQ pod.

=== `rabbitmq.resources.limits.memory`

[horizontal]
type:: string
default:: `3Gi`

The memory limit for RabbitMQ containers.

=== `rabbitmq.resources.limits.cpu`

[horizontal]
type:: string
default:: `1`

The CPU limit for RabbitMQ containers.

=== `rabbitmq.resources.requests.memory`

[horizontal]
type:: string
default:: `3Gi`

The memory request for RabbitMQ containers.

=== `rabbitmq.resources.requests.cpu`

[horizontal]
type:: string
default:: `1`

The CPU request for RabbitMQ containers.

=== `rabbitmq.replicas`

[horizontal]
type:: integer
default:: `3`

The number of RabbitMQ replicas to deploy.

=== `rabbitmq.tls.enabled`

[horizontal]
type:: boolean
default:: `false`

Whether to enable TLS for RabbitMQ connections.

=== `rabbitmq.tls.secretName`

[horizontal]
type:: string
default:: `rabbitmq-certs`

The name of the Kubernetes secret containing TLS certificates.

=== `rabbitmq.tls.disableNonTLSListeners`

[horizontal]
type:: boolean
default:: `true`

Whether to disable non-TLS listeners when TLS is enabled.

=== `rabbitmq.tls.dnsNames.amqps`

[horizontal]
type:: string
default:: `amqps.rabbitmq.com`

The DNS name for the AMQPS endpoint.

=== `rabbitmq.tls.dnsNames.management`

[horizontal]
type:: string
default:: `management.rabbitmq.com`

The DNS name for the management interface.

=== `rabbitmq.rbac.enabled`

[horizontal]
type:: boolean
default:: `false`

Whether to create RBAC resources for accessing RabbitMQ.

=== `rabbitmq.rbac.groups`

[horizontal]
type:: array
default:: `[]`

An array of group names to grant access to RabbitMQ resources.

=== `rabbitmq.rbac.group`

[horizontal]
type:: string
default:: `""`

A single group name to grant access to RabbitMQ resources.
This is a deprecated legacy option; prefer `rabbitmq.rbac.groups`.
If the same group is listed in both, it is only granted once.

=== `rabbitmq.service`

[horizontal]
type:: dictionary
default:: `{}`

The service configuration for the `RabbitmqCluster` resource.
The value of this parameter is used as-is for `spec.service` of the resulting resource.

IMPORTANT: The only fields supported by the operator are `type` and `annotations`.

=== `rabbitmq.ciliumNetworkPolicy.enabled`

[horizontal]
type:: boolean
default:: `false`

Whether to deploy a `CiliumNetworkPolicy` which allows traffic on `5671/tcp` and `5672/tcp` from outside the cluster (Cilium entity `world`).
This policy ensures that accessing the RabbitMQ cluster over an LB service works correctly on Cilium-enabled clusters.

Network policies to allow access from within the cluster must be managed separately.

=== `rabbitmq.custom_lb_service.enabled`

[horizontal]
type:: boolean
default:: `false`

When this parameter is set to true, the component deploys an Espejote `ManagedResource` which creates a copy of the `RabbitmqCluster`-owned primary service with `spec.type=LoadBalancer` and a configurable `spec.loadBalancerClass`.
For environments, where setting `spec.loadBalancerClass` isn't required, users should prefer setting `rabbitmq.service.type=LoadBalancer`.

The `ManagedResource` copies the primary service's `metadata.annotations`, `spec.ports` and `spec.selector`.
Users that want to customize the LoadBalancer service via annotations -- for example for requesting specific IPs from Cilium LB-IPAM -- should add these annotations in `rabbitmq.service.annotations`.
This should simplify removing this feature if the operator gains support for custom `spec.loadBalancerClass` in the future.

=== `rabbitmq.custom_lb_service.loadBalancerClass`

[horizontal]
type:: string
default:: `""`

This parameter allows users to provide a load balancer class names for the custom LoadBalancer service.
The value is used as `spec.loadBalancerClass` for the LB service without any validation.

== Prober Configuration

=== `prober.enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy the RabbitMQ health prober for SLA monitoring.

=== `prober.name`

[horizontal]
type:: string
default:: `rabbitmq-prober`

The name of the prober deployment.

=== `prober.image`

[horizontal]
type:: string
default:: `ghcr.io/projectsyn/component-rabbitmq-operator/prober:latest`

The container image for the RabbitMQ prober.

=== `prober.secretName`

[horizontal]
type:: string
default:: `rabbitmq-default-user`

The name of the Kubernetes secret containing RabbitMQ credentials for the prober.

=== `prober.probeInterval`

[horizontal]
type:: string
default:: `10`

The interval in seconds between health probes.

=== `prober.metricsPort`

[horizontal]
type:: integer
default:: `8080`

The port on which the prober exposes Prometheus metrics.

=== `prober.useTLS`

[horizontal]
type:: string
default:: `true`

Whether the prober should use TLS to connect to RabbitMQ.

=== `prober.alerts.enabled`

[horizontal]
type:: boolean
default:: `false`

Whether to create Prometheus alert rules for the prober.

=== `prober.resources.requests.memory`

[horizontal]
type:: string
default:: `64Mi`

The memory request for the prober container.

=== `prober.resources.requests.cpu`

[horizontal]
type:: string
default:: `50m`

The CPU request for the prober container.

=== `prober.resources.limits.memory`

[horizontal]
type:: string
default:: `128Mi`

The memory limit for the prober container.

=== `prober.resources.limits.cpu`

[horizontal]
type:: string
default:: `100m`

The CPU limit for the prober container.

=== `prober.monitoring.interval`

[horizontal]
type:: string
default:: `10s`

The interval at which Prometheus scrapes prober metrics.

=== `prober.monitoring.recordingRulesInterval`

[horizontal]
type:: string
default:: `10s`

The interval for Prometheus recording rules evaluation.

== Examples

=== Basic RabbitMQ Cluster

[source,yaml]
----
parameters:
  rabbitmq_operator:
    rabbitmq:
      enabled: true
      name: my-rabbitmq
      namespace: production
      replicas: 3
      plugins:
        - rabbitmq_shovel
        - rabbitmq_shovel_management
----

=== RabbitMQ with TLS

[source,yaml]
----
parameters:
  rabbitmq_operator:
    rabbitmq:
      enabled: true
      tls:
        enabled: true
        secretName: rabbitmq-tls-certs
        dnsNames:
          amqps: rabbitmq.example.com
          management: rabbitmq-mgmt.example.com
----

=== RabbitMQ with SLA Monitoring

[source,yaml]
----
parameters:
  rabbitmq_operator:
    rabbitmq:
      enabled: true
    prober:
      enabled: true
      probeInterval: '30'
      alerts:
        enabled: true
----

=== RabbitMQ with Additional Configuration

[source,yaml]
----
parameters:
  rabbitmq_operator:
    rabbitmq:
      resources:
        limits:
          memory: 4Gi  # <1>
      additionalConfig: |
        channel_max = 100
----
<1> `vm_memory_high_watermark.absolute` is automatically set to this value (`4Gi`).
Any entries in `additionalConfig` are appended after it.

=== RabbitMQ with Node Affinity

[source,yaml]
----
parameters:
  rabbitmq_operator:
    rabbitmq:
      enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: ["rabbitmq"]
----
